[package]
name = "practice"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bio = "0.39.0"

[[bin]]
name = "w1"
path = "src/main_w1.rs"

[[bin]]
name = "w2"
path = "src/main_w2.rs"
